window.PORTFOLIO_PROJECTS = [
  {
    id: "editorial-noir",
    order: 1,
    title: "Editorial Noir",
    category: "Estilismo de Moda",
    year: "2026",
    client: "Editorial Independiente",
    description: "Una historia de moda monocromática construida alrededor del volumen, la sombra y el carácter.",
    color: "#282828",
    image: "assets/images/project-01.jpg",
    gallery: ["assets/images/project-01.jpg", "assets/images/project-02.jpg", "assets/images/project-03.jpg", "assets/images/project-04.jpg", "assets/images/project-05.jpg", "assets/images/project-06.jpg"],
    keywords: ["Sombra", "Volumen", "Carácter"]
  },
  {
    id: "new-volume",
    order: 2,
    title: "Nuevo Volumen",
    category: "Estilismo de Vestuario",
    year: "2026",
    client: "Campaña de Moda",
    description: "Una exploración visual de silueta, proporción y sastrería contemporánea.",
    color: "#3b2119",
    image: "assets/images/project-02.jpg",
    gallery: ["assets/images/project-02.jpg", "assets/images/project-03.jpg", "assets/images/project-04.jpg", "assets/images/project-05.jpg", "assets/images/project-06.jpg", "assets/images/project-07.jpg"],
    keywords: ["Silueta", "Proporción", "Estructura"]
  },
  {
    id: "electric-blue",
    order: 3,
    title: "Azul Eléctrico",
    category: "Dirección Creativa",
    year: "2025",
    client: "Campaña Digital",
    description: "Una serie de imágenes de alta energía que combina color gráfico y estilismo directo.",
    color: "#1c2c49",
    image: "assets/images/project-03.jpg",
    gallery: ["assets/images/project-03.jpg", "assets/images/project-04.jpg", "assets/images/project-05.jpg", "assets/images/project-06.jpg", "assets/images/project-07.jpg", "assets/images/project-08.jpg"],
    keywords: ["Color", "Energía", "Ritmo"]
  },
  {
    id: "after-hours",
    order: 4,
    title: "Fuera de Horario",
    category: "Estilismo de Moda",
    year: "2025",
    client: "Editorial",
    description: "Sastrería nocturna, tensión cinematográfica y glamour discreto.",
    color: "#211619",
    image: "assets/images/project-04.jpg",
    gallery: ["assets/images/project-04.jpg", "assets/images/project-05.jpg", "assets/images/project-06.jpg", "assets/images/project-07.jpg", "assets/images/project-08.jpg", "assets/images/project-01.jpg"],
    keywords: ["Noche", "Tensión", "Sastrería"]
  },
  {
    id: "soft-structure",
    order: 5,
    title: "Estructura Suave",
    category: "Estilismo E-commerce",
    year: "2025",
    client: "Retail",
    description: "Una historia de producto refinada que equilibra suavidad, forma y claridad comercial.",
    color: "#5a544b",
    image: "assets/images/project-05.jpg",
    gallery: ["assets/images/project-05.jpg", "assets/images/project-06.jpg", "assets/images/project-07.jpg", "assets/images/project-08.jpg", "assets/images/project-01.jpg", "assets/images/project-02.jpg"],
    keywords: ["Suavidad", "Forma", "Claridad"]
  },
  {
    id: "red-signal",
    order: 6,
    title: "Señal Roja",
    category: "Estilismo de Campaña",
    year: "2024",
    client: "Marca de Moda",
    description: "Un lenguaje de campaña audaz definido por contraste, repetición y acentos rojos.",
    color: "#49120b",
    image: "assets/images/project-06.jpg",
    gallery: ["assets/images/project-06.jpg", "assets/images/project-07.jpg", "assets/images/project-08.jpg", "assets/images/project-01.jpg", "assets/images/project-02.jpg", "assets/images/project-03.jpg"],
    keywords: ["Contraste", "Repetición", "Impacto"]
  },
  {
    id: "summer-line",
    order: 7,
    title: "Línea de Verano",
    category: "Estilismo de Moda",
    year: "2024",
    client: "Editorial Comercial",
    description: "Siluetas livianas y luz saturada con un ritmo sin esfuerzo.",
    color: "#6f5b45",
    image: "assets/images/project-07.jpg",
    gallery: ["assets/images/project-07.jpg", "assets/images/project-08.jpg", "assets/images/project-01.jpg", "assets/images/project-02.jpg", "assets/images/project-03.jpg", "assets/images/project-04.jpg"],
    keywords: ["Luz", "Movimiento", "Ligereza"]
  },
  {
    id: "studio-forms",
    order: 8,
    title: "Formas de Estudio",
    category: "Estilismo E-commerce",
    year: "2024",
    client: "Estudio Retail",
    description: "Un sistema de estudio enfocado en estilismo consistente, silueta y narrativa de producto.",
    color: "#2f2f2f",
    image: "assets/images/project-08.jpg",
    gallery: ["assets/images/project-08.jpg", "assets/images/project-01.jpg", "assets/images/project-02.jpg", "assets/images/project-03.jpg", "assets/images/project-04.jpg", "assets/images/project-05.jpg"],
    keywords: ["Sistema", "Consistencia", "Producto"]
  }
];
